//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaVentas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class APERTURACAJA
    {
        public int APERNUM { get; set; }
        public int CAJANUMERO { get; set; }
        public int CAJRUT { get; set; }
        public System.DateTime APERFECHA { get; set; }
        public int APERMONTO { get; set; }
        public Nullable<int> APERSALDO { get; set; }
        public Nullable<bool> APERCERRADO { get; set; }
    }
}
