//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaVentas.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SisVentasEntities : DbContext
    {
        public SisVentasEntities()
            : base("name=SisVentasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<APERTURACAJA> APERTURACAJA { get; set; }
        public DbSet<CAJERO> CAJERO { get; set; }
        public DbSet<CLASE> CLASE { get; set; }
        public DbSet<COMPRA_DETALLE> COMPRA_DETALLE { get; set; }
        public DbSet<COMPRAS> COMPRAS { get; set; }
        public DbSet<INVENTARIO> INVENTARIO { get; set; }
        public DbSet<INVENTARIO_DETALLE> INVENTARIO_DETALLE { get; set; }
        public DbSet<MOVIMIENTOS> MOVIMIENTOS { get; set; }
        public DbSet<NATURALEZA> NATURALEZA { get; set; }
        public DbSet<PRIVILEGIOS> PRIVILEGIOS { get; set; }
        public DbSet<PROVEEDORES> PROVEEDORES { get; set; }
        public DbSet<SALIDAPRODUCTOS> SALIDAPRODUCTOS { get; set; }
        public DbSet<SUBCLASE> SUBCLASE { get; set; }
        public DbSet<TIPOPAGO> TIPOPAGO { get; set; }
        public DbSet<USUARIOS> USUARIOS { get; set; }
        public DbSet<VENTA_DETALLE> VENTA_DETALLE { get; set; }
        public DbSet<VENTAS> VENTAS { get; set; }
        public DbSet<Naturaleza_Clase> Naturaleza_Clase { get; set; }
        public DbSet<PRODUCTOS> PRODUCTOS { get; set; }
        public DbSet<UNIDAD_MEDIDA> UNIDAD_MEDIDA { get; set; }
        public DbSet<ProductosListados> ProductosListados { get; set; }
    }
}
