//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaVentas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPRA_DETALLE
    {
        public int COMDETID { get; set; }
        public int COMPID { get; set; }
        public int PRODCODIGO { get; set; }
        public decimal COMPCANTIDAD { get; set; }
        public string COMPCODIGOBARRA { get; set; }
        public int COMPMONTOLINEA { get; set; }
    }
}
