//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaVentas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPRAS
    {
        public int COMPID { get; set; }
        public string PROVRUT { get; set; }
        public int CAJRUT { get; set; }
        public System.DateTime COMFECHA { get; set; }
        public byte COMPFORMAPAGO { get; set; }
        public long COMPNUMDOCTO { get; set; }
        public long COMPMONTO { get; set; }
    }
}
