//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaVentas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTARIO_DETALLE
    {
        public int INVLINEA { get; set; }
        public int INVNUMERO { get; set; }
        public int PRODCODIGO { get; set; }
        public decimal INVCANTIDAD { get; set; }
        public string INVCODIGOBARRA { get; set; }
    }
}
