//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaVentas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVIMIENTOS
    {
        public int MOVNUMERO { get; set; }
        public int APERNUM { get; set; }
        public int MOVTIPO { get; set; }
        public Nullable<int> MOVNUMDOCUMENTO { get; set; }
        public Nullable<int> MOVTIPODOCTO { get; set; }
        public int MOVMONTO { get; set; }
        public string MOVOBSERVACIONES { get; set; }
    }
}
