//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaVentas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductosListados
    {
        public int CodNat { get; set; }
        public int CodClase { get; set; }
        public int CodSubClase { get; set; }
        public int CodProducto { get; set; }
        public string Producto { get; set; }
        public Nullable<int> Precio { get; set; }
        public string CodBarra { get; set; }
        public decimal StockInicial { get; set; }
        public decimal StockActual { get; set; }
        public bool Inventariable { get; set; }
        public string Naturaleza { get; set; }
        public string Clase { get; set; }
        public string SubClase { get; set; }
    }
}
