//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaVentas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVEEDORES
    {
        public string PROVRUT { get; set; }
        public string PROVRAZON { get; set; }
        public string PROVDIRECCION { get; set; }
        public string PROVTELEFONO { get; set; }
        public string PROVEMAIL { get; set; }
        public string PROVVENDEDOR { get; set; }
        public string PROVFONOVENDEDOR { get; set; }
    }
}
