//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaVentas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALIDAPRODUCTOS
    {
        public int SALID { get; set; }
        public System.DateTime SALFECHA { get; set; }
        public int CAJRUT { get; set; }
        public int PRODCODIGO { get; set; }
        public string SALCODBARRA { get; set; }
        public decimal SALCANTIDAD { get; set; }
        public string SALOBSERVACION { get; set; }
    }
}
