//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaVentas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTA_DETALLE
    {
        public long VENTADETID { get; set; }
        public long VENTAID { get; set; }
        public int VENTLINEA { get; set; }
        public decimal VENTCANTIDAD { get; set; }
        public int PRODCODIGO { get; set; }
        public string VENTCODBARRA { get; set; }
        public int VENTTOTLINEA { get; set; }
    }
}
