//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaVentas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTAS
    {
        public long VENTAID { get; set; }
        public byte TIPPAGOID { get; set; }
        public int CAJRUT { get; set; }
        public int VENBOLETANUM { get; set; }
        public System.DateTime VENTFECHA { get; set; }
        public int VENTOTAL { get; set; }
        public int VENTACANCELADO { get; set; }
        public int VENTAVUELTO { get; set; }
        public Nullable<long> VENBOUCHER { get; set; }
    }
}
